// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {graph} from '../models';
import {context} from '../models';

export function GetGraph(arg1:string):Promise<graph.Graph>;

export function SetContext(arg1:context.Context):Promise<void>;
