// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGraph(arg1) {
  return window['go']['wailshandler']['GraphHandler']['GetGraph'](arg1);
}

export function SetContext(arg1) {
  return window['go']['wailshandler']['GraphHandler']['SetContext'](arg1);
}
