// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CopyImage(arg1:string,arg2:string,arg3:string):Promise<string>;

export function PickImage():Promise<string>;

export function ReadImageBase64(arg1:string,arg2:string):Promise<string>;

export function SaveImageBase64(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;
