// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {plugin} from '../models';
import {context} from '../models';

export function GetPluginData(arg1:string,arg2:string):Promise<string>;

export function ListPlugins():Promise<Array<plugin.Plugin>>;

export function LoadPluginSource(arg1:string):Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetPluginData(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetPluginEnabled(arg1:string,arg2:boolean):Promise<void>;
