// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPluginData(arg1, arg2) {
  return window['go']['wailshandler']['PluginHandler']['GetPluginData'](arg1, arg2);
}

export function ListPlugins() {
  return window['go']['wailshandler']['PluginHandler']['ListPlugins']();
}

export function LoadPluginSource(arg1) {
  return window['go']['wailshandler']['PluginHandler']['LoadPluginSource'](arg1);
}

export function SetContext(arg1) {
  return window['go']['wailshandler']['PluginHandler']['SetContext'](arg1);
}

export function SetPluginData(arg1, arg2, arg3) {
  return window['go']['wailshandler']['PluginHandler']['SetPluginData'](arg1, arg2, arg3);
}

export function SetPluginEnabled(arg1, arg2) {
  return window['go']['wailshandler']['PluginHandler']['SetPluginEnabled'](arg1, arg2);
}
