// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {search} from '../models';
import {context} from '../models';

export function SearchFiles(arg1:string,arg2:string):Promise<Array<search.SearchResult>>;

export function SetContext(arg1:context.Context):Promise<void>;
