// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {volt} from '../models';
import {context} from '../models';

export function CreateVolt(arg1:string,arg2:string):Promise<volt.Volt>;

export function DeleteVolt(arg1:string):Promise<void>;

export function ListVolts():Promise<Array<volt.Volt>>;

export function SelectDirectory():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;
